services:

  postgres-app:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      TZ: UTC
    ports:
      - 5433:5432
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  Database for storing keycloak data
  postgres-keycloak:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${KC_DB_NAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    ports:
      - 9090:8080
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    networks:
      - backend
    command: start-dev

#  UI admin for database
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    networks:
      - backend
    depends_on:
      postgres-app:
        condition: service_healthy

volumes:
  app_db_data:
  keycloak_db_data:

networks:
  backend:
    driver: bridge

# In real production setups, Keycloak uses PostgreSQL.
## Port Nature
## Host Port : Container Port
